### ISSUE TITLE
Equipment Module

### ISSUE THREAD

**Issue by zaphon** [hizuro/Broker_Everything#2]
The equipment module is broken in that it makes the assumption that all equipment sets are stored sequentially. This isn't guaranteed as the ID is assigned at creation, and if any sets are deleted in between the ID is not updated. There are 2 locations where you iterate as follows

`for i=0, numEquipSets do`

If you change both to

`for __, i in pairs(C_EquipmentSet.GetEquipmentSetIDs()) do`

It fixes it and all sets display correctly.

**Comment by hizuro** [comment]
Thank you for reporting.
Update is available.

**Comment by zaphon** [comment]
There were 2 places where this occurred. Also at line 49-53 which was missed.

**Comment by hizuro** [comment]
Oops. Thanks. ;-)

**Comment by zaphon** [comment]
Hate to nitpick but looks like with the last fix line 220 appears to be inverted (you say no sets found if there is a set).

**Comment by hizuro** [comment]
"Hate to nitpick" don't worry, it doesn't bother me. ;-)
Thank you again...
